
-- This is a replacment for cabal's autogenerated Paths_nikki.hs
-- Use this instead to find data files.
-- Needed for deployment in one folder (e.g. on windows)

module Paths (getDataFileName) where


import System.Info

import qualified Paths_nikki


getDataFileName :: FilePath -> IO FilePath
getDataFileName = case os of
    "linux" -> Paths_nikki.getDataFileName
    "mingw32" -> return -- works if the application is deployed in one folder
    x -> error ("unsupported os: " ++ os)
