resolver: lts-3.22
flags:
  nikki:
    devel: true
packages:
  - ./.
  - scripts
  - level-server
extra-deps:
  - binary-communicator-1.0.2.2
  - bindings-libzip-1.0.1
  - clocked-0.4.1.3
  - crypto-pubkey-types-0.1.1
  - FindBin-0.0.5
  - Hipmunk-5.2.0.17
  - LibZip-1.0.1
  - network-fancy-0.2.4
  - RSA-1.2.1.0
  - stickyKeysHotKey-0.1.0.2
  - git: https://github.com/nikki-and-the-robots/sfml-audio
    commit: 499eaf9b6f6a964a611bbd5693dc744295db9147
