name: ci

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master

env:
  CACHE_KEY: 1

jobs:
  all:
    name: all
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.stack
            src/.stack-work
          key: ${{ env.CACHE_KEY }}-${{ runner.os }}

      - name: info
        run: stack --version

      - name: install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get remove libzip4
          sudo apt-get install -t bionic libzip-dev
          sudo apt-get install \
            cmake curl g++ libopenal-dev libqt4-dev libsndfile1-dev pkg-config

      - name: build qtwrapper
        run: |
          cd src
          ./build-qtwrapper.sh

      - name: build haskell executables
        run: |
          cd src
          stack build -j1

      - name: test
        run: |
          cd src
          stack test -j1
